---
general-en:
  title: General Roman Calendar
  language: en
  files:
    - universal-en.txt
    
general-it: &default
  title: Calendario Romano
  language: it
  files:
    - universal-it.txt
default:
  <<: *default
